[ET-VK][testing] Add scripts to facilitate operator testiing
Pull Request resolved: https://github.com/pytorch/executorch/pull/13593

Title says it all. All scripts to help with building + running operator tests. Also fixes an error with building these tests.

CI will be added at a later date. Currently the tests cannot be built on Linux due to an unrelated error

```
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp: In member function ‘virtual void OperatorRegistryTest_RegisterKernels_Test::TestBody()’:
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp:307:20: error: could not convert ‘(executorch::runtime::EValue**)(& kernels)’ from ‘executorch::runtime::EValue**’ to ‘executorch::runtime::Span<executorch::runtime::EValue*>’
  307 |   (*func)(context, kernels);
      |                    ^~~~~~~
      |                    |
      |                    executorch::runtime::EValue**
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp: In member function ‘virtual void OperatorRegistryTest_RegisterTwoKernels_Test::TestBody()’:
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp:373:22: error: could not convert ‘(executorch::runtime::EValue**)(& evalues)’ from ‘executorch::runtime::EValue**’ to ‘executorch::runtime::Span<executorch::runtime::EValue*>’
  373 |   (*func_1)(context, evalues);
      |                      ^~~~~~~
      |                      |
      |                      executorch::runtime::EValue**
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp:384:22: error: could not convert ‘(executorch::runtime::EValue**)(& evalues)’ from ‘executorch::runtime::EValue**’ to ‘executorch::runtime::Span<executorch::runtime::EValue*>’
  384 |   (*func_2)(context, evalues);
      |                      ^~~~~~~
      |                      |
      |                      executorch::runtime::EValue**
[ 66%] Building CXX object kernels/portable/CMakeFiles/portable_kernels.dir/cpu/op_cat.cpp.o
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp: In member function ‘virtual void OperatorRegistryTest_ExecutorUsesKernel_Test::TestBody()’:
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp:485:20: error: could not convert ‘(executorch::runtime::EValue**)(& kernels)’ from ‘executorch::runtime::EValue**’ to ‘executorch::runtime::Span<executorch::runtime::EValue*>’
  485 |   (*func)(context, kernels);
      |                    ^~~~~~~
      |                    |
      |                    executorch::runtime::EValue**
[ 67%] Building CXX object kernels/portable/CMakeFiles/portable_kernels.dir/cpu/op_cdist_forward.cpp.o
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp: In member function ‘virtual void OperatorRegistryTest_ExecutorUsesFallbackKernel_Test::TestBody()’:
/home/ssjia/Github/executorch/runtime/kernel/test/operator_registry_test.cpp:513:20: error: could not convert ‘(executorch::runtime::EValue**)(& kernels)’ from ‘executorch::runtime::EValue**’ to ‘executorch::runtime::Span<executorch::runtime::EValue*>’
  513 |   (*func)(context, kernels);
      |                    ^~~~~~~
      |                    |
      |                    executorch::runtime::EValue**
```


@imported-using-ghimport

Differential Revision: [D80800081](https://our.internmc.facebook.com/intern/diff/D80800081/)
ghstack-source-id: 305143839